# Generated by Django 6.0 on 2026-01-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_formapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userEntry',
        ),
    ]
